# Generated by Django 3.0.2 on 2020-08-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200829_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='stripe_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
