# Generated by Django 3.0.2 on 2020-08-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('short_desc', models.CharField(max_length=80, verbose_name='Short Description')),
                ('description', models.TextField(default='', max_length=5000, verbose_name='Full Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, verbose_name='Discount Price')),
                ('image', models.ImageField(default='', upload_to='prod_pics', verbose_name='Product Image')),
                ('category', models.CharField(choices=[('arrival', 'Arrival'), ('album', 'Album')], max_length=30, verbose_name='Category')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Publisher', verbose_name='Author')),
                ('songs', models.ManyToManyField(blank=True, help_text='Choose if category is album', related_name='_product_songs_+', to='products.Product', verbose_name='Songs')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
